### ISSUE TITLE
Filter select controls do not populate when data height defined

### ISSUE THREAD

**Issue by DazzaL** [wenzhixin/bootstrap-table#6434]
### Bootstraptable version(s) affected

1.21.1

### Description

This looks like a regression of #6004 possibly?

have a combination of 
 data-filter-control="true"
and
  data-height="460"

now try to filter on a select dropdown. While the select does now get populated, the value is not retained after the table completes its search, the selection goes blank. see the prebuilt example as per #6004 here: https://live.bootstrap-table.com/code/UtechtDustin/10038

Choose say $7 as the filter. The table will filter as requested, but then the filter selection displays a blank instead of retaining $7.

### Example(s)

https://live.bootstrap-table.com/code/UtechtDustin/10038

### Possible Solutions

remove the data height- resulting in a poor UI experience.

**Comment by MahmoudAbdElMoneam** [comment]
I have Sticky-Header, and Cookie extensions enabled.
I got it fixed in my project by adding in the bootstrap-table-filter-control.js the lines under this line:
//Added to fix the input selection lost after filter is applied

```Javascript
 function initFilterSelectControls(that) {
   var data = that.options.data;
   $.each(that.header.fields, function (j, field) {
     var column = that.columns[that.fieldsColumnsIndex[field]];
     var selectControl = getControlContainer(that).find("select.bootstrap-table-filter-control-".concat(escapeID(column.field)));
     if (isColumnSearchableViaSelect(column) && isFilterDataNotGiven(column) && hasSelectControlElement(selectControl)) {
       if (!selectControl[0].multiple && selectControl.get(selectControl.length - 1).options.length === 0) {
         // Added the default option, must use a non-breaking space(&nbsp;) to pass the W3C validator
         addOptionToSelectControl(selectControl, '', column.filterControlPlaceholder || ' ', column.filterDefault);
       }
       var uniqueValues = {};
       for (var i = 0; i < data.length; i++) {
         // Added a new value
         var fieldValue = Utils$1.getItemField(data[i], field, false);
         var formatter = that.options.editable && column.editable ? column._formatter : that.header.formatters[j];
         var formattedValue = Utils$1.calculateObjectValue(that.header, formatter, [fieldValue, data[i], i], fieldValue);
         if (fieldValue === undefined || fieldValue === null) {
           fieldValue = formattedValue;
           column._forceFormatter = true;
         }
         if (column.filterDataCollector) {
           formattedValue = Utils$1.calculateObjectValue(that.header, column.filterDataCollector, [fieldValue, data[i], formattedValue], formattedValue);
         }
         if (column.searchFormatter) {
           fieldValue = formattedValue;
         }
         uniqueValues[formattedValue] = fieldValue;
         if (_typeof(formattedValue) === 'object' && formattedValue !== null) {
           formattedValue.forEach(function (value) {
             addOptionToSelectControl(selectControl, value, value, column.filterDefault);
           });
           continue;
         }
       }        
       // eslint-disable-next-line guard-for-in
         for (var key in uniqueValues) {
             //Added to fix the input selection lost after filter is applied
             if (that.filterColumnsPartial != null &&
                 Object.keys(that.filterColumnsPartial).includes(field)) {
                 var targetSearchValue = that.filterColumnsPartial[field];
                 if (key == targetSearchValue)
                     column.filterDefault = that.filterColumnsPartial[field];
                 else
                     column.filterDefault = "";
             }
             else if (column.filterDefault != "")
                 column.filterDefault = "";
               //End of added code
           addOptionToSelectControl(selectControl, uniqueValues[key], key, column.filterDefault);
         }
       if (that.options.sortSelectOptions) {
         sortSelectControl(selectControl, column.filterOrderBy, that.options);
       }
     }
   });
 }
```

**Comment by theogray** [comment]
Thanks @MahmoudAbdElMoneam, those extra lines appear to solve the issue for me as well. I'm using Cookie extension (but not Sticky-Header).

**Update**: As the extra code only runs when isFilterDataNotGiven returns true, then for columns that have filterData defined, the bug still happens for just those columns, and so it's not then possible to remove the filter on those columns without reloading.

Something along these lines based on the above then works for both cases but I'm unsure what other state/metadata might need to be set. Reloading the page for example still appears to lose the cookie-stored filter setting for columns with 'select' filters (the cookie is stored correctly but during reload when 'column-search' is triggered multiple times, then eventually the filtered values in 'select' columns are lost).
```
if (that.filterColumnsPartial != null
           && Object.keys(that.filterColumnsPartial).includes(field)
) {
    var targetSearchValue = that.filterColumnsPartial[field];
    var testValue = Utils$1.unescapeHTML(targetSearchValue);
    var options = getOptionsFromSelectControl(selectControl);
    for (var i = 0; i < options.length; i++) {
        if (options[i].value !== testValue) continue;
        options[i].selected = true;
        break;
    }
}
```
